;;; !!! This configuration is handled by HelloImGui and stores several Ini Files, separated by markers like this:
           ;;;<<<INI_NAME>>>;;;

;;;<<<ImGui_655921752_Default>>>;;;
[Window][Debug##Default]
Pos=60,60
Size=400,400
Collapsed=0
LastUsed=20260816

[Window][GudCam Live Super-Resolution Inspection]
Pos=39,25
Size=1256,1039
Collapsed=0
DockId=0x00000002,0
LastUsed=20260816

[Window][Pipeline Telemetry & Kernel Metrics]
Pos=1297,25
Size=408,1039
Collapsed=0
DockId=0x00000003,0
LastUsed=20260816

[Window][Dynamic V4L2 Hardware Controls]
Pos=1473,136
Size=420,500
Collapsed=0
LastUsed=20260816

[Docking][Data]
DockNode    ID=0x00000001 Pos=39,25 Size=1666,1039 Split=X
  DockNode  ID=0x00000002 Parent=0x00000001 SizeRef=1256,1039 Selected=0x6378FF43
  DockNode  ID=0x00000003 Parent=0x00000001 SizeRef=408,1039 Selected=0xF28716E8

;;;<<<Layout_655921752_Default>>>;;;
;;;<<<HelloImGui_Misc>>>;;;
[Layout]
Name=Default
[StatusBar]
Show=false
ShowFps=true
[Theme]
Name=DarculaDarker
;;;<<<SplitIds>>>;;;
{"gImGuiSplitIDs":{}}
