;;; !!! This configuration is handled by HelloImGui and stores several Ini Files, separated by markers like this:
           ;;;<<<INI_NAME>>>;;;

;;;<<<ImGui_655921752_Default>>>;;;
[Window][Debug##Default]
Pos=60,60
Size=400,400
Collapsed=0
LastUsed=20260816

[Window][GudCam Live Super-Resolution Inspection]
Pos=486,68
Size=821,622
Collapsed=0
LastUsed=20260816

[Window][Pipeline Telemetry & Kernel Metrics]
Pos=60,60
Size=408,733
Collapsed=0
LastUsed=20260816

[Window][Dynamic V4L2 Hardware Controls]
Pos=1361,64
Size=420,500
Collapsed=0
LastUsed=20260816

[Docking][Data]

;;;<<<Layout_655921752_Default>>>;;;
;;;<<<HelloImGui_Misc>>>;;;
[Layout]
Name=Default
[StatusBar]
Show=false
ShowFps=true
[Theme]
Name=DarculaDarker
;;;<<<SplitIds>>>;;;
{"gImGuiSplitIDs":{}}
